import OurTeam from '@/components/OurTeam/OurTeam'
import Projects from '@/components/Projects/Projects'
import Services from '@/components/Services/Services'
import Head from 'next/head'
import CardWrapper from '../components/Card/CardWrapper'
import Header from '../components/Header/Header'
import HeroSection from '../components/HeroSection/HeroSection'
import BrandLogo from '../components/BrandLogo/BrandLogo'
import WorksSection from '../components/WorksSection/WorksSection'
import Testimonials from '@/components/Testimonials/Testimonials'
import Callout from '@/components/Callout/Callout'
import Footer from '@/components/Footer/Footer'

export default function Home() {
  const Links = [
    {
      text: 'Services',
      url: '/'
    },
    {
      text: 'How We Work',
      url: '/'
    },
    {
      text: 'Projects',
      url: '/'
    },
    {
      text: 'About',
      url: '/'
    }
  ]

  return (
    <>
      <Head>
        <title>Collosal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Header Links={Links} />
        <HeroSection />
        <CardWrapper />
        <BrandLogo />
        <WorksSection />
        <OurTeam />
        <Projects />
        <Services />
        <Testimonials />
        <Callout />
        <Footer />
      </>
    </>
  )
}
